# Generated by Django 5.2.16 on 2026-07-24 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario_nombre', models.CharField(blank=True, help_text='Copia congelada del username. La FK es SET_NULL: sin esto, borrar un usuario dejaría media bitácora sin autor, que es lo único que no puede pasar.', max_length=150)),
                ('accion', models.CharField(choices=[('EMPLEADO_CREADO', 'Empleado creado'), ('EMPLEADO_ACTUALIZADO', 'Empleado actualizado'), ('EMPLEADO_FOTO_CAMBIADA', 'Foto de empleado cambiada'), ('EMPLEADO_FOTO_ELIMINADA', 'Foto de empleado eliminada'), ('RELACION_CREADA', 'Relación laboral creada'), ('RELACION_FINALIZADA', 'Relación laboral finalizada (baja)'), ('DOCUMENTO_CREADO', 'Documento cargado'), ('DOCUMENTO_ACTUALIZADO', 'Documento actualizado'), ('DOCUMENTO_ELIMINADO', 'Documento eliminado'), ('NOVEDAD_CREADA', 'Novedad creada'), ('NOVEDAD_ACTUALIZADA', 'Novedad actualizada'), ('NOVEDAD_APROBADA', 'Novedad aprobada'), ('NOVEDAD_RECHAZADA', 'Novedad rechazada'), ('NOVEDAD_ANULADA', 'Novedad anulada'), ('NOVEDAD_PRORROGADA', 'Novedad prorrogada'), ('CADENA_ANULADA', 'Cadena de prórrogas anulada'), ('ADJUNTO_AGREGADO', 'Adjunto agregado a novedad'), ('ADJUNTO_ELIMINADO', 'Adjunto eliminado de novedad'), ('CHECKLIST_ITEM_COMPLETADO', 'Ítem de checklist completado'), ('CHECKLIST_ITEM_REVERTIDO', 'Ítem de checklist destildado'), ('USUARIO_CREADO', 'Usuario creado'), ('USUARIO_ACTUALIZADO', 'Usuario actualizado'), ('USUARIO_DESACTIVADO', 'Usuario desactivado')], db_index=True, max_length=40)),
                ('entidad', models.CharField(help_text='Nombre del modelo afectado ("Empleado", "Novedad"…).', max_length=50)),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, help_text='PK del objeto. Queda null si el objeto se borró.', null=True)),
                ('objeto_repr', models.CharField(blank=True, help_text='Texto legible del objeto al momento del hecho ("Pérez, Juan (leg. 0042)"). Congelado: si el objeto se borra o se renombra, la bitácora sigue diciendo de quién hablaba.', max_length=200)),
                ('valores_antes', models.JSONField(blank=True, default=dict, help_text='Solo los campos que cambiaron. {} en un alta.')),
                ('valores_despues', models.JSONField(blank=True, default=dict, help_text='Solo los campos que cambiaron. {} en una baja.')),
                ('ip', models.GenericIPAddressField(blank=True, help_text='Origen de la request. Sin llenar en MVP1: los services reciben el actor, no la request. Se completa con un middleware cuando haga falta, sin migración.', null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Null si lo hizo un proceso automático, o si el usuario se borró después.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-momento', '-id'],
                'indexes': [models.Index(fields=['entidad', 'objeto_id', '-momento'], name='idx_audit_objeto'), models.Index(fields=['usuario', '-momento'], name='idx_audit_usuario')],
            },
        ),
    ]
