# Generated by Django 5.2.16 on 2026-07-24 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('empleados', '0004_empleado_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='empleado',
            field=models.ForeignKey(blank=True, help_text="De qué PERSONA habla el evento, aunque `entidad` sea otra cosa. Denormalizado a propósito: sin esto, 'el historial de la ficha de Juan' obliga a juntar eventos de Empleado, RelacionLaboral, DocumentoEmpleado, Novedad e ItemProceso averiguando antes cuáles son de Juan. Null en eventos que no son de nadie en particular (un usuario del sistema sin empleado asociado).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='empleados.empleado'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['empleado', '-momento'], name='idx_audit_empleado'),
        ),
    ]
