# Generated by Django 5.2.16 on 2026-07-24 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_bitacora_append_only'),
        ('empleados', '0006_documento_por_relacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('EMPLEADO_CREADO', 'Empleado creado'), ('EMPLEADO_ACTUALIZADO', 'Empleado actualizado'), ('EMPLEADO_FOTO_CAMBIADA', 'Foto de empleado cambiada'), ('EMPLEADO_FOTO_ELIMINADA', 'Foto de empleado eliminada'), ('EMPLEADO_CONSULTADO', 'Ficha sensible consultada'), ('DOCUMENTO_DESCARGADO', 'Documento sensible descargado'), ('FOTO_CONSULTADA', 'Foto de empleado consultada'), ('RELACION_CREADA', 'Relación laboral creada'), ('RELACION_FINALIZADA', 'Relación laboral finalizada (baja)'), ('DOCUMENTO_CREADO', 'Documento cargado'), ('DOCUMENTO_ACTUALIZADO', 'Documento actualizado'), ('DOCUMENTO_ELIMINADO', 'Documento eliminado'), ('NOVEDAD_CREADA', 'Novedad creada'), ('NOVEDAD_ACTUALIZADA', 'Novedad actualizada'), ('NOVEDAD_APROBADA', 'Novedad aprobada'), ('NOVEDAD_RECHAZADA', 'Novedad rechazada'), ('NOVEDAD_ANULADA', 'Novedad anulada'), ('NOVEDAD_PRORROGADA', 'Novedad prorrogada'), ('CADENA_ANULADA', 'Cadena de prórrogas anulada'), ('ADJUNTO_AGREGADO', 'Adjunto agregado a novedad'), ('ADJUNTO_ELIMINADO', 'Adjunto eliminado de novedad'), ('ADJUNTO_DESCARGADO', 'Adjunto de novedad descargado'), ('CHECKLIST_ITEM_COMPLETADO', 'Ítem de checklist completado'), ('CHECKLIST_ITEM_REVERTIDO', 'Ítem de checklist destildado'), ('PLANTILLA_CREADA', 'Plantilla de checklist creada'), ('PLANTILLA_PUBLICADA', 'Plantilla de checklist publicada'), ('PLANTILLA_ARCHIVADA', 'Plantilla de checklist archivada'), ('PLANTILLA_ITEM_CREADO', 'Ítem de plantilla creado'), ('PLANTILLA_ITEM_ACTUALIZADO', 'Ítem de plantilla actualizado'), ('CHECKLIST_INICIADO', 'Proceso de checklist iniciado'), ('CATALOGO_CREADO', 'Elemento de catálogo creado'), ('CATALOGO_ACTUALIZADO', 'Elemento de catálogo actualizado'), ('CONFIG_ACTUALIZADA', 'Configuración actualizada'), ('USUARIO_CREADO', 'Usuario creado'), ('USUARIO_ACTUALIZADO', 'Usuario actualizado'), ('USUARIO_DESACTIVADO', 'Usuario desactivado'), ('USUARIO_PASSWORD_CAMBIADA', 'Contraseña de usuario cambiada'), ('SESION_INICIADA', 'Sesión iniciada'), ('SESION_CERRADA', 'Sesión cerrada')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='empleado',
            field=models.ForeignKey(blank=True, help_text="De qué PERSONA habla el evento, aunque `entidad` sea otra cosa. Denormalizado a propósito: sin esto, 'el historial de la ficha de Juan' obliga a juntar eventos de Empleado, RelacionLaboral, DocumentoEmpleado, Novedad e ItemProceso averiguando antes cuáles son de Juan. Null en eventos que no son de nadie en particular (un usuario del sistema sin empleado asociado). La persona referenciada no puede borrarse físicamente.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='usuario_nombre',
            field=models.CharField(blank=True, help_text='Copia congelada del username para conservar el dato legible aunque el nombre de usuario cambie.', max_length=150),
        ),
    ]
