# Generated by Django 5.2.16 on 2026-07-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_bloquear_truncate_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('EMPLEADO_CREADO', 'Empleado creado'), ('EMPLEADO_ACTUALIZADO', 'Empleado actualizado'), ('EMPLEADO_FOTO_CAMBIADA', 'Foto de empleado cambiada'), ('EMPLEADO_FOTO_ELIMINADA', 'Foto de empleado eliminada'), ('EMPLEADO_CONSULTADO', 'Ficha sensible consultada'), ('DOCUMENTO_DESCARGADO', 'Documento sensible descargado'), ('FOTO_CONSULTADA', 'Foto de empleado consultada'), ('RELACION_CREADA', 'Relación laboral creada'), ('RELACION_FINALIZADA', 'Relación laboral finalizada (baja)'), ('RELACION_SUPERVISOR_CAMBIADO', 'Supervisor de relación cambiado'), ('DOCUMENTO_CREADO', 'Documento cargado'), ('DOCUMENTO_ACTUALIZADO', 'Documento actualizado'), ('DOCUMENTO_ELIMINADO', 'Documento eliminado'), ('NOVEDAD_CREADA', 'Novedad creada'), ('NOVEDAD_ACTUALIZADA', 'Novedad actualizada'), ('NOVEDAD_TOMADA', 'Novedad tomada en proceso'), ('NOVEDAD_APROBADA', 'Novedad aprobada'), ('NOVEDAD_RECHAZADA', 'Novedad rechazada'), ('NOVEDAD_CERRADA', 'Novedad cerrada'), ('NOVEDAD_ANULADA', 'Novedad anulada'), ('NOVEDAD_PRORROGADA', 'Novedad prorrogada'), ('CADENA_ANULADA', 'Cadena de prórrogas anulada'), ('ADJUNTO_AGREGADO', 'Adjunto agregado a novedad'), ('ADJUNTO_ELIMINADO', 'Adjunto eliminado de novedad'), ('ADJUNTO_DESCARGADO', 'Adjunto de novedad descargado'), ('CHECKLIST_ITEM_COMPLETADO', 'Ítem de checklist completado'), ('CHECKLIST_ITEM_REVERTIDO', 'Ítem de checklist destildado'), ('PLANTILLA_CREADA', 'Plantilla de checklist creada'), ('PLANTILLA_PUBLICADA', 'Plantilla de checklist publicada'), ('PLANTILLA_ARCHIVADA', 'Plantilla de checklist archivada'), ('PLANTILLA_ITEM_CREADO', 'Ítem de plantilla creado'), ('PLANTILLA_ITEM_ACTUALIZADO', 'Ítem de plantilla actualizado'), ('CHECKLIST_INICIADO', 'Proceso de checklist iniciado'), ('CATALOGO_CREADO', 'Elemento de catálogo creado'), ('CATALOGO_ACTUALIZADO', 'Elemento de catálogo actualizado'), ('CONFIG_ACTUALIZADA', 'Configuración actualizada'), ('USUARIO_CREADO', 'Usuario creado'), ('USUARIO_ACTUALIZADO', 'Usuario actualizado'), ('USUARIO_DESACTIVADO', 'Usuario desactivado'), ('USUARIO_PASSWORD_CAMBIADA', 'Contraseña de usuario cambiada'), ('SESION_INICIADA', 'Sesión iniciada'), ('SESION_CERRADA', 'Sesión cerrada')], db_index=True, max_length=40),
        ),
    ]
