# Generated by Django 5.2.16 on 2026-07-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('razon_social', models.CharField(blank=True, max_length=150)),
                ('cuit', models.CharField(blank=True, max_length=15)),
                ('zona_horaria', models.CharField(default='America/Argentina/Buenos_Aires', help_text='P5: hoy todas operan en la misma zona; el campo evita bloquear el futuro.', max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.JSONField(default=dict)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'parámetro',
                'verbose_name_plural': 'parámetros',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'puesto',
                'verbose_name_plural': 'puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'sector',
                'verbose_name_plural': 'sectores',
                'ordering': ['nombre'],
            },
        ),
    ]
