# Generated by Django 5.2.16 on 2026-07-09 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='referente_rrhh',
            field=models.ForeignKey(blank=True, help_text='Destinatario de los avisos de la empresa (D9 del cross-check §21).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_referenciadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parametro',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puesto',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sector',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puesto',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='organizacion.sector'),
        ),
    ]
