# Generated by Django 5.2.16 on 2026-07-09 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('dni', models.CharField(db_index=True, max_length=15, unique=True)),
                ('cuil', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('id_huella', models.CharField(blank=True, db_index=True, help_text='Ej. HUELLA-0042. Se guarda desde MVP1 para el matching biométrico futuro (P2).', max_length=50, null=True, unique=True)),
                ('exento_marcacion', models.BooleanField(default=False, help_text='P2: empleados exonerados de marcar. En MVP1 es solo dato.')),
                ('educacion', models.CharField(blank=True, choices=[('PRIMARIO_INCOMPLETO', 'Primario incompleto'), ('PRIMARIO_COMPLETO', 'Primario completo'), ('SECUNDARIO_INCOMPLETO', 'Secundario incompleto'), ('SECUNDARIO_COMPLETO', 'Secundario completo'), ('TERCIARIO', 'Terciario'), ('UNIVERSITARIO', 'Universitario')], max_length=25)),
                ('contacto_emergencia', models.CharField(blank=True, help_text='Nombre · vínculo · teléfono (un solo campo en MVP1).', max_length=200)),
                ('obra_social', models.CharField(blank=True, max_length=100)),
                ('art', models.CharField(blank=True, help_text='Aseguradora de riesgos del trabajo.', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(blank=True, help_text='Solo si el empleado accede al sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RelacionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_ingreso', models.DateField(help_text='Base de antigüedad (spec §1.7).')),
                ('jornada_legal', models.CharField(blank=True, choices=[('COMPLETA_8H', 'Completa (8h)'), ('REDUCIDA_6H', 'Reducida (6h)'), ('MEDIA_4H', 'Media (4h)'), ('ROTATIVA', 'Rotativa')], max_length=15)),
                ('tipo_contrato', models.CharField(choices=[('INDETERMINADO', 'Indeterminado'), ('PLAZO_FIJO', 'Plazo fijo'), ('EVENTUAL', 'Eventual'), ('TEMPORADA', 'Temporada'), ('PASANTIA', 'Pasantía')], default='INDETERMINADO', max_length=15)),
                ('fecha_vencimiento_contrato', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=10)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('motivo_egreso', models.CharField(blank=True, choices=[('RENUNCIA', 'Renuncia'), ('FIN_CONTRATO', 'Fin de contrato'), ('DESPIDO', 'Despido'), ('JUBILACION', 'Jubilación'), ('MUDANZA', 'Mudanza'), ('OTRO', 'Otro')], max_length=30)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones', to='empleados.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones', to='organizacion.empresa')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relaciones', to='organizacion.puesto')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relaciones', to='organizacion.sector')),
            ],
            options={
                'verbose_name': 'relación laboral',
                'verbose_name_plural': 'relaciones laborales',
                'ordering': ['-fecha_ingreso'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('empleado', 'empresa'), name='uniq_relacion_activa_por_empresa')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, db_index=True, help_text='La query de alertas filtra por acá.', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='empleados.empleado')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='empleados.tipodocumento')),
            ],
            options={
                'verbose_name': 'documento de empleado',
                'verbose_name_plural': 'documentos de empleados',
                'ordering': ['empleado', 'tipo_documento'],
                'constraints': [models.UniqueConstraint(fields=('empleado', 'tipo_documento'), name='uniq_documento_vigente_por_tipo')],
            },
        ),
    ]
