# Generated by Django 5.2.16 on 2026-07-15 18:04

import apps.empleados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoempleado',
            name='archivo',
            field=models.FileField(blank=True, help_text='Respaldo escaneado (PDF/imagen). Opcional: el control de vencimientos funciona con la fecha sola, y RRHH puede cargar el vencimiento antes de tener el scan. Se descarga solo por el endpoint protegido, nunca por URL directa.', upload_to=apps.empleados.models.ruta_archivo_documento),
        ),
    ]
