# Generated by Django 5.2.16 on 2026-07-15 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_documentoempleado_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='dias_aviso',
            field=models.PositiveSmallIntegerField(default=30, help_text='Días de anticipación con que se avisa el vencimiento de este documento.', validators=[django.core.validators.MaxValueValidator(180)]),
        ),
    ]
