# Generated by Django 5.2.16 on 2026-07-21 02:24

import apps.empleados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_tipodocumento_dias_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.FileField(blank=True, help_text='Foto de perfil (imagen raster). Se sirve por endpoint protegido, no por URL directa. FileField y no ImageField para no atar el repo a Pillow.', upload_to=apps.empleados.models.ruta_archivo_foto),
        ),
    ]
