# Generated by Django 5.2.16 on 2026-07-24 13:06

import re

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


_SEPARADORES_DOCUMENTO = re.compile(r"[\s.-]+")
_DNI_CANONICO = re.compile(r"^[0-9]{6,9}$")
_CUIL_CANONICO = re.compile(r"^[0-9]{11}$")


def _dni(valor):
    normalizado = _SEPARADORES_DOCUMENTO.sub("", str(valor or ""))
    if not _DNI_CANONICO.fullmatch(normalizado):
        raise ValueError("debe contener entre 6 y 9 dígitos")
    return normalizado


def _cuil(valor):
    normalizado = _SEPARADORES_DOCUMENTO.sub("", str(valor or ""))
    if not normalizado:
        return None
    if not _CUIL_CANONICO.fullmatch(normalizado):
        raise ValueError("debe contener 11 dígitos")
    return normalizado


def _huella(valor):
    normalizado = str(valor or "").strip().upper()
    if not normalizado:
        return None
    if len(normalizado) > 50:
        raise ValueError("supera 50 caracteres después de normalizar")
    return normalizado


def preflight_y_normalizar_identificadores(apps, schema_editor):
    """Valida todo el legado antes de ejecutar el primer UPDATE."""
    Empleado = apps.get_model("empleados", "Empleado")
    alias = schema_editor.connection.alias
    filas = list(
        Empleado.objects.using(alias)
        .order_by("id")
        .values("id", "dni", "cuil", "id_huella")
    )
    normalizadores = {
        "dni": _dni,
        "cuil": _cuil,
        "id_huella": _huella,
    }
    vistos = {campo: {} for campo in normalizadores}
    filas_normalizadas = []
    invalidos = []

    for fila in filas:
        valores = {}
        fila_valida = True
        for campo, normalizador in normalizadores.items():
            try:
                valor = normalizador(fila[campo])
            except ValueError as error:
                fila_valida = False
                invalidos.append(
                    f"empleado id={fila['id']} campo={campo}: {error}"
                )
                continue
            valores[campo] = valor
            if valor is not None:
                vistos[campo].setdefault(valor, []).append(fila["id"])
        if fila_valida:
            filas_normalizadas.append((fila["id"], valores))

    colisiones = []
    for campo, valores in vistos.items():
        for _valor, ids in valores.items():
            if len(ids) > 1:
                colisiones.append(
                    f"campo={campo} colisiona entre empleados ids={ids}"
                )

    problemas = invalidos + colisiones
    if problemas:
        detalle = "\n - ".join(problemas)
        raise RuntimeError(
            "Preflight de identificadores abortado; no se modificó ninguna fila. "
            "Corregí los siguientes datos y reintentá:\n - "
            f"{detalle}"
        )

    # Recién después de validar formatos y unicidad del conjunto completo se escribe.
    objetos = []
    for empleado_id, valores in filas_normalizadas:
        objetos.append(Empleado(pk=empleado_id, **valores))
    if objetos:
        Empleado.objects.using(alias).bulk_update(
            objetos,
            ["dni", "cuil", "id_huella"],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_documento_por_relacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            preflight_y_normalizar_identificadores,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuil',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(db_index=True, max_length=9, unique=True),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.CheckConstraint(condition=models.Q(('dni__regex', '^[0-9]{6,9}$')), name='empleado_dni_normalizado'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.CheckConstraint(condition=models.Q(('cuil__isnull', True), ('cuil__regex', '^[0-9]{11}$'), _connector='OR'), name='empleado_cuil_normalizado'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.CheckConstraint(condition=models.Q(('id_huella__isnull', True), models.Q(models.Q(('id_huella', ''), _negated=True), models.Q(('id_huella__regex', '(^\\s)|(\\s$)'), _negated=True), ('id_huella', django.db.models.functions.text.Upper('id_huella'))), _connector='OR'), name='empleado_huella_normalizada'),
        ),
    ]
