# Generated by Django 5.2.16 on 2026-07-23 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0004_empleado_foto'),
        ('organizacion', '0004_puesto_constraint_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_proceso', models.CharField(choices=[('INGRESO', 'Onboarding (ingreso)'), ('EGRESO', 'Offboarding (egreso)')], max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_checklist', to='organizacion.empresa')),
            ],
            options={
                'verbose_name': 'plantilla de checklist',
                'verbose_name_plural': 'plantillas de checklist',
                'ordering': ['empresa', 'tipo_proceso'],
            },
        ),
        migrations.CreateModel(
            name='ItemPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Posición del renglón en la lista (menor primero).')),
                ('etiqueta', models.CharField(max_length=120)),
                ('tipo_item', models.CharField(choices=[('ACCION', 'Acción (se tilda a mano)'), ('DOCUMENTAL', 'Documental (enlazado a un documento del legajo)')], default='ACCION', max_length=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(blank=True, help_text='Solo para ítems DOCUMENTAL: el tipo de documento del legajo que lo completa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_checklist', to='empleados.tipodocumento')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onboarding.plantillachecklist')),
            ],
            options={
                'verbose_name': 'ítem de plantilla',
                'verbose_name_plural': 'ítems de plantilla',
                'ordering': ['plantilla', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_proceso', models.CharField(choices=[('INGRESO', 'Onboarding (ingreso)'), ('EGRESO', 'Offboarding (egreso)')], max_length=10)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(blank=True, help_text='Plantilla que se fotografió al crear el proceso (referencia; puede quedar null).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos', to='onboarding.plantillachecklist')),
                ('relacion_laboral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_checklist', to='empleados.relacionlaboral')),
            ],
            options={
                'verbose_name': 'proceso de checklist',
                'verbose_name_plural': 'procesos de checklist',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('etiqueta', models.CharField(max_length=120)),
                ('tipo_item', models.CharField(choices=[('ACCION', 'Acción (se tilda a mano)'), ('DOCUMENTAL', 'Documental (enlazado a un documento del legajo)')], max_length=12)),
                ('completado', models.BooleanField(default=False)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('completado_por', models.ForeignKey(blank=True, help_text='Quién tildó el ítem de acción (constancia).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_plantilla', models.ForeignKey(blank=True, help_text='Renglón de origen (referencia); puede quedar null si la plantilla cambia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_proceso', to='onboarding.itemplantilla')),
                ('tipo_documento', models.ForeignKey(blank=True, help_text='Foto del tipo de documento para ítems DOCUMENTAL (el que los completa).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_proceso', to='empleados.tipodocumento')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onboarding.procesoempleado')),
            ],
            options={
                'verbose_name': 'ítem de proceso',
                'verbose_name_plural': 'ítems de proceso',
                'ordering': ['proceso', 'orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='plantillachecklist',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('empresa', 'tipo_proceso'), name='uniq_plantilla_activa_por_empresa_tipo'),
        ),
        migrations.AddConstraint(
            model_name='itemplantilla',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo_documento__isnull', False), ('tipo_item', 'DOCUMENTAL')), models.Q(('tipo_documento__isnull', True), ('tipo_item', 'ACCION')), _connector='OR'), name='item_documental_exige_tipo_documento'),
        ),
        migrations.AddConstraint(
            model_name='procesoempleado',
            constraint=models.UniqueConstraint(fields=('relacion_laboral', 'tipo_proceso'), name='uniq_proceso_por_relacion_tipo'),
        ),
    ]
