# Generated by Django 5.2.16 on 2026-07-10 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.SlugField(help_text='Ej. LICENCIA_MEDICA, HORAS_EXTRA.', max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('justifica_ausencia', models.BooleanField(default=False)),
                ('requiere_certificado', models.BooleanField(default=False)),
                ('admite_prorroga', models.BooleanField(default=False)),
                ('requiere_cantidad_horas', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tipo de novedad',
                'verbose_name_plural': 'tipos de novedad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_desde', models.DateField(db_index=True)),
                ('fecha_hasta', models.DateField(blank=True, help_text='Null = abierta (p. ej. licencia sin alta médica).', null=True)),
                ('cantidad_horas', models.DecimalField(blank=True, decimal_places=2, help_text='Solo tipos con requiere_cantidad_horas (HORAS_EXTRA manual, P4).', max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EN_PROCESO', 'En proceso'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='REGISTRADA', max_length=12)),
                ('clasificacion', models.CharField(blank=True, choices=[('JUSTIFICADA', 'Justificada'), ('INJUSTIFICADA', 'Injustificada')], max_length=13)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_aviso_empleado', models.DateField(blank=True, help_text='Cuándo avisó el empleado (del front).', null=True)),
                ('requiere_praxis', models.BooleanField(default=False, help_text='Marca intervención de ART / seguimiento médico.')),
                ('fecha_turno_praxis', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_reintegro', models.DateField(blank=True, null=True)),
                ('certificado_recibido_en', models.DateField(blank=True, help_text="Alerta 'sin certificado tras X días' (spec §1.3).", null=True)),
                ('generada_automaticamente', models.BooleanField(default=False, help_text='Distingue el cross-check automático de la carga manual.')),
                ('aprobada_en', models.DateTimeField(blank=True, null=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='empleados.empleado')),
                ('novedad_origen', models.ForeignKey(blank=True, help_text='Prórrogas: apunta SIEMPRE a la novedad madre de la cadena (§6 bis).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prorrogas', to='novedades.novedad')),
                ('relacion_laboral', models.ForeignKey(blank=True, help_text='Contexto empresa/contrato; por defecto la relación activa del empleado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='empleados.relacionlaboral')),
                ('tipo_novedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='novedades.tiponovedad')),
            ],
            options={
                'verbose_name': 'novedad',
                'verbose_name_plural': 'novedades',
                'ordering': ['-fecha_desde', '-id'],
            },
        ),
    ]
