# Generated by Django 5.2.16 on 2026-07-15 13:10
#
# B3: respaldo en la base de la regla de no-solapamiento. El ExclusionConstraint no puede
# hacer JOIN a TipoNovedad, así que `ocupa_periodo` se denormaliza como columna de Novedad
# (la mantiene Novedad.save()) y acá se rellena para las filas que ya existen.

import apps.novedades.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


def copiar_ocupa_periodo_del_tipo(apps_registry, schema_editor):
    """Las novedades ya cargadas heredan el flag de su tipo (una query por tipo, no por fila)."""
    Novedad = apps_registry.get_model("novedades", "Novedad")
    Novedad.objects.filter(tipo_novedad__ocupa_periodo=True).update(ocupa_periodo=True)


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('novedades', '0002_tiponovedad_ocupa_periodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # El constraint mezcla igualdad (empleado) con solapamiento de rangos (&&) en un
        # mismo índice GiST: eso solo lo permite btree_gist.
        BtreeGistExtension(),
        migrations.AddField(
            model_name='novedad',
            name='ocupa_periodo',
            field=models.BooleanField(default=False, editable=False, help_text='Copia de tipo_novedad.ocupa_periodo, mantenida en save(). Existe solo porque un ExclusionConstraint no puede hacer JOIN a TipoNovedad: la regla de no-solapamiento necesita el flag como columna propia. No editar a mano.'),
        ),
        # Backfill antes del constraint: si en la base ya hay novedades solapadas (cargadas
        # cuando la regla solo vivía en Python), el AddConstraint de abajo va a fallar. Es
        # deliberado — hay que corregir esos datos, no bajar la guardia.
        migrations.RunPython(
            copiar_ocupa_periodo_del_tipo, migrations.RunPython.noop, elidable=False
        ),
        migrations.AddConstraint(
            model_name='novedad',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('estado__in', ('REGISTRADA', 'EN_PROCESO', 'APROBADA', 'CERRADA')), ('ocupa_periodo', True)), expressions=[('empleado', '='), (apps.novedades.models._RangoDeFechas('fecha_desde', 'fecha_hasta', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&')], name='excl_novedades_solapadas_por_empleado'),
        ),
    ]
