# Generated by Django 5.2.16 on 2026-07-15 22:24

import apps.novedades.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0003_novedad_ocupa_periodo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to=apps.novedades.models.ruta_archivo_adjunto)),
                ('nombre_original', models.CharField(help_text="El nombre con el que se subió. En disco el archivo es un UUID, pero en una bitácora saber que un adjunto era 'radiografia.jpg' y otro 'certificado.pdf' es justamente el dato: acá no hay un tipo que lo diga, como sí lo hay en los documentos del empleado.", max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Null cuando lo crea un proceso automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='novedades.novedad')),
            ],
            options={
                'verbose_name': 'adjunto de novedad',
                'verbose_name_plural': 'adjuntos de novedades',
                'ordering': ['creado_en', 'id'],
            },
        ),
    ]
